### ISSUE TITLE
case sensitive has no significance if language is not None

### ISSUE THREAD

**Issue by cbsnagur** [barrust/pyspellchecker#104]
![image](https://user-images.githubusercontent.com/24971177/117141334-098b7480-adcc-11eb-9da9-28d6d1c8d336.png)

issue is mainly bcz in init, 
case sensitivity is considered only if language is None, else case sensitivity is False. 

code line:
47. self._case_sensitive = case_sensitive if not language else False

I know preloaded dict is has lower case-sensitive words but if i want to add few additionaly words to preloaded dict, which i want to be case-sensitive i cannot achieve that, 

issue can be resolved if we updated the check in init, 

was there any specific reason why it was done so?

**Comment by barrust** [comment]
You are correct that one cannot add case-sensitive words to the default language dictionaries. There are several reasons for this but a few of them are:
* Many of the words in the original dictionary would also need to be capitalized
* Reduces computation time in determining distance
* By keeping the built-in dictionaries all lowercase reduces the possible issues of people mistakenly adding case-sensitive words.   

If you want to add case-sensitive words you can export the dictionary and reload it as case-sensitive. Then you would be able to add to the dictionary.
