### ISSUE TITLE
Unable to read dictionary 

### ISSUE THREAD

**Issue by mahmoud-alsahlee** [barrust/pyspellchecker#105]
I am using python version 3.9.5 My .py program is running fine with spell check but when I convert from .py to .exe and run it throws me an error:
ValueError: The provided dictionary language (en) does not exist!
I tried other languages and the same message still remaining.

Kindly help

**Comment by mahmoud-alsahlee** [comment]
the problem was in installing the pyspellchecker using :
pip install pyspellchecker

to solve this issue use the sources installer as in the documentation:

git clone https://github.com/barrust/pyspellchecker.git
cd pyspellchecker
python setup.py install

**Comment by barrust** [comment]
That is interesting. I am glad you found a work around. The documentation has some information on how one can use PyInstaller to convert to an .exe without having to go through the manual installation. 

Anyways, glad it is working for you!
