### ISSUE TITLE
dictionary inconsistency

### ISSUE THREAD

**Issue by mhillendahl** [barrust/pyspellchecker#115]
Python 3.9.5
Windows 10 x64

**Expected Behavior**
Each language setting only contains itself. Words written in a different language, deliberately or by mistake, are _unknown_.

**Observed Behavior**
Each language appears to contain itself plus one or more additional language(s).
_en_ contains words from English as expected, but also from Spanish, French, and German.
_es_ contains words from Spanish as expected, but also from English and French.
_fr_ contains words from French as expected, but also from English.
_pt_ contains words from Portuguese as expected, but also from English.
_de_ contains words from German as expected, but also from English.

**Impact**
Typos in the selected language are undetectable if they incidentally match one of the extra languages. (see console output below)

**Steps to Reproduce**

spellCheckerTest.py
``` python
from spellchecker import SpellChecker

langs = ['en', 'es', 'fr', 'pt', 'de']
words = ['word', 'palabra', 'mot', 'palavra', 'wort', 'notaword']

for i in range(5):
    lang = SpellChecker(language=langs[i])
    known = lang.known(words)
    unknown = lang.unknown(words)
    print(f'{langs[i]} : {", ".join(sorted(known))} ({", ".join(sorted(unknown))})')
    
input()
```
console output
```
en : mot, palabra, word, wort (notaword, palavra)
es : mot, palabra, word (notaword, palavra, wort)
fr : mot, word (notaword, palabra, palavra, wort)
pt : palavra, word (mot, notaword, palabra, wort)
de : word, wort (mot, notaword, palabra, palavra)
```

**Comment by barrust** [comment]
The data used to build the dictionaries are pulled from the [opensubtitles](http://www.opensubtitles.org/) project. The build process is automated using [script/build_dictionaries.py](https://github.com/barrust/pyspellchecker/blob/master/scripts/build_dictionary.py). I don't know of a good method to automatically find and flag each of these "cross-overs" but any help in making the build_dictionaries.py script more robust would be appreciated.

**Comment by stephencawood** [comment]
There are almost 1.5 million entries in the English dictionary. It's clear that there are far too many. But it's not just French, Spanish, and German. For example:

"開かれた": 1,
"闇を切り裂いてさ": 2,
"阎东生": 1,
"阿昭": 1,
"降り出した雪": 10,
"限りがあるってのを知っていてムダにしちゃうんだろう": 2,
"陽のあたる場所に登りたい": 1,
"隙間から顔を出す": 1,
"隠し場所": 1,
"離れれば知らぬこと": 1,
"電流火花が身体を走る": 1,
"霸府": 8,
"青": 1,
"青い夜の静けさを行く": 2,
"青い鳥は僕らの目の前で": 1,
"青い麦の海": 1,
"青ざめった町並": 2,
"青リンゴ": 7,
"青空に": 1,
"願": 2,
"願いが叶っても": 1,
"願いを繰り返す": 1,
"顾小丹": 1,
"颗": 1,
"風": 1,
"風が頬をなでる": 1,
"風を呼んでデカイ帆をはれ": 3,
"風遁:空砂防壁": 2,
"马蚤": 1,
"髭が濃い": 1,
"魚さま": 1,
"鯉": 1,
"鶴翼の陣": 2,
"鸥扼": 1,
"鸥扼瘤": 1,
"麦の波を": 1,
"麦迪逊": 1,
"齁": 1,
"국제시장": 1,
"꿢nd": 1,
"꿣ut": 1,
"나": 1,
