### ISSUE TITLE
installing from source instructions outdated

### ISSUE THREAD

**Issue by nsheils** [barrust/pyspellchecker#135]
In the instructions for how to install from source: 
`git clone https://github.com/barrust/pyspellchecker.git 
cd pyspellchecker
python setup.py install
`

However, within hte pyspellchecker folder there is no setup.py file.

**Comment by barrust** [comment]
Good catch. I moved to PEP 517 support and didn't update the readme. I believe it should be how to build from source and no longer install from source.
