### ISSUE TITLE
PyPI entry points to wrong package

### ISSUE THREAD

**Issue by stevejalim** [barrust/pyspellchecker#143]
Hi - an update to the following lines to reference this project, not pyprobables, would help users find this repo more easily.

https://github.com/barrust/pyspellchecker/blob/05505ca41515d4ae436caf6ac21885c278a10658/pyproject.toml#L41-L44

Thanks!

**Comment by barrust** [comment]
Wow, good catch. I guess these happened when I was moving my packages away from setup.py!
