### ISSUE TITLE
Error in load file function 

### ISSUE THREAD

**Issue by ron-oren97** [barrust/pyspellchecker#151]
I stumbled upon an error being raised by the function load_file in utils.py (line 95) that is called from spellchecker.py (line 436).
The error I got: 
"..\spellchecker\utils.py", line 105, in load_file
    if filename[-3:].lower() == ".gz":
       ~~~~~~~~^^^^^
TypeError: 'WindowsPath' object is not subscriptable

**Comment by barrust** [comment]
This error is because the library doesn't officially offer support for Path objects. I am working on a full solution to ensure that path objects are supported in full.
