### ISSUE TITLE
Dozens of words are detected as wrong in German, though very common

### ISSUE THREAD

**Issue by MaestroGlanz** [barrust/pyspellchecker#155]
Väter is unknown, Brüder is unknown, ertöne (Imperativ singular + first person singular of ertönen).

Also upper/lower case must match the input. There is no word like "männer", only "Männer"

The spellchecker is close to unusable under such conditions.

**Comment by barrust** [comment]
Sorry there are errors. The data comes from OpenSubtitles. Any help (PR) in cleaning up dictionaries or suggestions for better open source data sources would be very helpful. 

Unfortunately, I am not a German speaker and don't know what to look for to clean it up.
