### ISSUE TITLE
Including common words in the "en.json.gz" resources

### ISSUE THREAD

**Issue by jocronin** [barrust/pyspellchecker#171]
Hi there! 

Just wondering if there was a reason why we don't see words like "i'm" and "i'll" in the words list but we see "they'll", "she'll" and "he'll". I noticed while using the package that "I'm" was being corrected to "ism".

Code to replicate:

```
from spellchecker import SpellChecker

spell = SpellChecker()

print(spell.candidates("i'm"))

>>{"h'm", 'ism'}

print(spell.candidates("i'll"))

>>{'ill', "it'll"}
```

Would it be possible to add these example to the known words list?
Cheers

**Comment by barrust** [comment]
This will be resolved in version `0.8.2`
