### ISSUE TITLE
'SpellChecker' object has no attribute 'word_probability'

### ISSUE THREAD

**Issue by DSnohwar** [barrust/pyspellchecker#174]
Has the word_probability function deprecated ? i want to get the confidence score for each of the candidates for a given word is there any other way?

**Comment by barrust** [comment]
Yes, it was deprecated in [Version 0.6.1](https://github.com/barrust/pyspellchecker/blob/master/CHANGELOG.md#version-061)

There is the `word_usage_frequency` function that replaced the old `word_probablity` since a true probability isn't being generated as it is actually a frequency.
