### ISSUE TITLE
Custom dictionary with hyphenated words

### ISSUE THREAD

**Issue by geodavic-cg** [barrust/pyspellchecker#176]
I have a custom dictionary that contains words like pierre-charest but the spellchecker can't correct a misspelling like piere-charest.  
### Discussed in https://github.com/barrust/pyspellchecker/discussions/90

<div type='discussions-op-text'>

<sup>Originally posted by **barrust** March  2, 2021</sup>
# Building and Using a Custom Dictionary

Building a custom dictionary is a great way to utilize the `pyspellchecker` library. This thread is based on issues that I have run across multiple times and I figured I would put a summary of all the information in a single location. This thread can be updated and added to as needed!

Building a custom dictionary is more preference than anything. Using external data sources can lead to misspellings to unexpectedly occur. This is even the case with the default dictionaries as they are built using the open source subtitles projects. That being said, here are a few tips.

* Find your source to use, usually as a text file
* Decide if the dictionary is to augment the data in a previous dictionary or if it is a stand alone dictionary.
* Once built (see below for examples) check for known errors and remove as needed
* Export dictionary and follow using and loading of custom dictionary tips

There are several methods to load data into a dictionary:

* [spell.word_frequency.load_dictionary()](https://pyspellchecker.readthedocs.io/en/latest/code.html#spellchecker.WordFrequency.load_dictionary)
* [spell.word_frequency.load_text()](https://pyspellchecker.readthedocs.io/en/latest/code.html#spellchecker.WordFrequency.load_text)
* [spell.word_frequency.load_json()](https://pyspellchecker.readthedocs.io/en/latest/code.html#spellchecker.WordFrequency.load_json)
* [spell.word_frequency.load_text_file()](https://pyspellchecker.readthedocs.io/en/latest/code.html#spellchecker.WordFrequency.load_text_file)
* [spell.word_frequency.load_words()](https://pyspellchecker.readthedocs.io/en/latest/code.html#spellchecker.WordFrequency.load_words)

Using one of the above function you can now build your custom dictionary.

#### Stand alone dictionary

This is a new language or person specific dictionary that is not built on a previous language. Make sure to not load a dictionary before building the new dictionary!
``` python
from spellchecker import SpellChecker

# if stand alone, make sure to use language=None
spell = SpellChecker(language=None)

spell.word_frequency.load_text_file('my_text_file.txt')
```

#### Adding to a default dictionary

In this case, it is recommended to act like it is a stand alone dictionary and set the *language* parameter to `None` and load the default dictionary before loading the custom dictionary. This will allow the user to get any future changes to the default dictionary.

``` python
from spellchecker import SpellChecker

spell = SpellChecker(language=None)

spell.word_frequency.load_text_file('my_text_file.txt')
```

#### Modifying a default dictionary

If you are planning to modify a default dictionary for personal use (not to be sent back to the library) then you will want to load the correct dictionary, modify and export it but then **do not** load the original dictionary again when using the updated, custom dictionary.

``` python
from spellchecker import SpellChecker

spell = SpellChecker()  # load the default English dictionary

# add words that are missing / needed
spell.word_frequency.load_text_file('my_text_file.txt')

# remove some things that are incorrect
spell.remove("the") # I don't like 'the'
```

Once the data is originally loaded, run some tests to ensure the data is as correct and as expected. Check for commonly misspelled words in your dictionary to make sure they are not present and also check for known words.

``` python
# check for some misspelled words
common_misspelled = ['tihs', 'alot']
for word in common_misspelled:
    if word in spell:
        spell.remove(word)

# make sure specific words are present
common_words = ['accept', 'another']
for word in common_misspelled:
    if word not in spell:
        spell[word] = 1  # put it in if missing
```

Once the data is set, the data can then be exported to be used in the future.

``` python
# generally, do not gzip the dictionary until it has been fully confirmed
# to be correct!
spell.export('my_custom_dict.json', gzipped=False)
```

## Using the Custom dictionary

The first major thing that trips up users is loading in the custom dictionary when another dictionary is already loaded. Thus, the user is getting a default dictionary and their custom dictionary.

For example:

``` python
from spellchecker import SpellChecker

spell = SpellChecker()  # Note: this loads in the English dictionary!
spell.load_dictionary("my_custom_dict.json")
```

Unless your custom dictionary is to augment the base dictionary, remember to setup the `SpellChecker` object without a language. There are two methods to easily accomplish this:

``` python
from spellchecker import SpellChecker

# option 1
spell = SpellChecker(language=None)
spell.load_dictionary("my_custom_dict.json")

# option 2
# this only loads the custom dictionary
spell2 = SpellChecker(local_dictionary="my_custom_dict.json")
```

The two options above are identical! If a filename, local_dictionary, is provided to the original creation, then the default languages are not loaded.

## Adding a New Supported Language

It is possible to provide a new language to `pyspellchecker`. The goal is that the building of dictionaries to be packaged with the library are able to be re-created as needed. To do this, you will need to update the [scripts/build_dictionary.py](https://github.com/barrust/pyspellchecker/blob/master/scripts/build_dictionary.py) script to support the language. Once that is updated, including all the necessary information, a new dictionary can be created and updated. It is the preferred method instead of submitting a PR with a new dictionary that cannot be re-created.

## Issues Creating New Dictionaries

If you are experiencing issues creating a new, custom dictionary, then please submit an issue. A good thing to provide will be the code used to verify the steps included in this discussion. You may be pointed here for "guidance" if the issue is not clear.

If you would like to share your experiences and tips, please add to the discussion!

Thanks!!
[@barrust](https://github.com/barrust)
</div>

**Comment by barrust** [comment]
Can you provide an example? The following test shows that it should work. 

``` python
from spellchecker import SpellChecker
spell = SpellChecker(language="en")
spell.word_frequency.add("test-123")  # add a hyphenated word

word = "test123"
print(spell.candidates(word))
```

**Comment by geodavic-cg** [comment]
Here is my code:

















*from spellchecker import SpellCheckerspell =
SpellChecker(language=None)spell.word_frequency.load_text_file("D:\\sdf\\cfg\\tnp\\address_word_freqs.json")#
find those words that may be misspelledmisspelled =
spell.unknown(['piere-charest'])for word in misspelled:    # Get the one
`most likely` answer    print(spell.correction(word))    # Get a list of
`likely` options    print(spell.candidates(word))
spell.word_frequency.add("pierre-charest")  # add a hyphenated wordword =
"piere-charest"print(spell.candidates(word))*

The output I get is:



*NoneNone{'pierre-charest'}*

The json file I load contains the following entry:

*"pierre-charest": 51,*

It appears it has something to do with this file...

**Comment by barrust** [comment]
I believe it is because you are loading the frequency list as a text file and not as a json file. 

Something like this should work:

``` python
from spellchecker import SpellChecker

PATH_TO_JSON = ""
local_dictionary = {"pierre-charest": 51}
spell = SpellChecker(language=None)
spell.word_frequency.load_json(local_dictionary)  # load a python dictionary / 
spell.word_frequency.load_dictionary(PATH_TO_JSON)  # load a json file as a dictionary
# find those words that may be misspelled
misspelled = spell.unknown(["piere-charest"])
print(misspelled)
for word in misspelled:  # Get the one`most likely` answer
    print(spell.correction(word))  # Get a list of`likely` options
    print(spell.candidates(word))
    spell.word_frequency.add("pierre-charest")  # add a hyphenated wordword = "piere-charest"
    print(spell.candidates(word))
```

**Comment by geodavic-cg** [comment]
Thanks, it worked. I must have mis-interpreted the examples you give on
loading your own dictionaries.
