### ISSUE TITLE
Version 0.2.0 is broken

### ISSUE THREAD

**Issue by marchezinixd** [barrust/pyspellchecker#24]
Hello again,
This time i'm here because the version 0.2.0 is broken for python 3. It needs the indexer library and this library is only available for python2. 
The version 0.1.5 have no errors.
Thanks

**Comment by barrust** [comment]
Not sure what you mean by the indexer library. It is passed all the tests. Can you provide a traceback of the error or where in the code you are seeing the issue?

**Comment by barrust** [comment]
Or, if you can provide sample code that would work too!

**Comment by marchezinixd** [comment]
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.5/dist-packages/spellchecker/__init__.py", line 2, in <module>
>     from  spellchecker.core import Spellchecker,getInstance
>   File "/usr/local/lib/python3.5/dist-packages/spellchecker/core.py", line 26, in <module>
>     from indexer import DictionaryIndex
> ImportError: No module named 'indexer'

**Comment by marchezinixd** [comment]
That's the error. Well the real problem is that when you try to install indexer lib in python 3

> Collecting indexer
>   Downloading https://files.pythonhosted.org/packages/c7/2f/49ea001ccc81502fe790c6077ca0cf9c4dc98ce160e1b1225a8c881b53b1/indexer-0.6.2.tar
> .gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-ude8to6g/indexer/setup.py", line 107
>         except OSError, ex:
>                       ^
>     SyntaxError: invalid syntax
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ude8to6g/indexer/

**Comment by barrust** [comment]
I don't know why that would be happening; if you check the source there are no calls to `indexer`. According to [this](https://github.com/facebook/prophet/issues/418#issuecomment-359106434) it could be that your `setup_tools` is out of date. Are you using `pip` or `pip3` to install =?

**Comment by marchezinixd** [comment]
Well i'v already tried everything, pip3 always throws that error, while pip from python 2 is istalling everything ok.
I checked the code, i could not find where you call indexer, but v0.1.5 works fine for me

**Comment by barrust** [comment]
I am at a loss since I have successfully installed v0.2.0 from multiple machines successfully. 

* Does installing it from source work? 
* If you download the wheel, does it work using `pip3 install --use-wheel --no-index <path to downloaded wheel>`? 

Everything I have read about it seems to point to pip3 and/or setup_tools being broken.

**Comment by barrust** [comment]
does something like this help:
```python-3.6 -m pip install pyspellchecker```
? Of course, with the correct python executable.

**Comment by MukhtarShaima** [comment]
hie,
i want to use this with Urdu language,is there a way to add urdu dict?

**Comment by barrust** [comment]
@MukhtarShaima This should be in a separate issue but there is nothing stopping a Urdu dictionary from being made. I download a word frequency list from [here](https://github.com/hermitdave/FrequencyWords) and then turn it into a JSON object where the key is the word and val is the count. You can then load that into pyspellchecker using code like the following:

``` python
from spellchecker import SpellChecker

urdu_dictionary_path = "path_to_urdu_dictionary_json"

spell = SpellChecker(language=None, local_dictionary=urdu_dictionary_path)
# use pyspellchecker as normal
```

You can also use pyspellchecker to help build the dictionary:
``` python
from spellchecker import SpellChecker
spell = SpellChecker(language=None)

# loop over words that you would like, adding common words more than less common words...
spell.export("path_to_urdu_dictionary")
```

Good luck!

**Comment by MukhtarShaima** [comment]
Thank you,
As the issue related to language was closed,so I thought reopening will not
be good,as I'm new to GitHub,so don't know much about it.

**Comment by barrust** [comment]
You can open a new issue asking how a language could be added or supported. I have no issues adding new languages or a specific language.

**Comment by vickydeshpande8** [comment]
A colleague of mine was facing this issue

Upon introspection it was discovered that he had install the module 'spellchecker' instead of 'pyspellchecker'. The line causing the error was in the file core.py related to 'spellchecker' and not 'pyspellchecker'

Upon uninstalling 'spellchecker' and installing 'pyspellchecker' instead, the issue was rectified.

**Comment by Sudarshan-gurav** [comment]
> does something like this help:
> `python-3.6 -m pip install pyspellchecker`
> ? Of course, with the correct python executable.
> pip install pyspellchecker successfully install in machine thank you sir

**Comment by chriseal** [comment]
I had this issue when working in a conda virtual environment (an error that didn't occur when I wasn't in that environment) and 'fixed' it by just doing `pip install pyspellchecker` (v0.5.0) instead of `pip install pyspellchecker==0.4.0`

**Comment by eclaassens** [comment]
I had the same error on MacOs in a conda environment. Problem I had was because I did pip install spellchecker in stead off pip install **py**spellchecker

**Comment by JordanRex** [comment]
^ i dont think installing the other spellchecker is necessary

**Comment by djdebonis** [comment]
I was running in anaconda but had installed using pip I believe. Entering this solved the issue for me:

```bash
conda install -c cogsci pyspellchecker
```

https://anaconda.org/cogsci/pyspellchecker

**Comment by bradbell** [comment]
> A colleague of mine was facing this issue
> 
> Upon introspection it was discovered that he had installed the module 'spellchecker' instead of 'pyspellchecker'. The line causing the error was in the file core.py related to 'spellchecker' and not 'pyspellchecker'
> 
> Upon uninstalling 'spellchecker' and installing 'pyspellchecker' instead, the issue was rectified.

Thanks for the tip. This also worked for me.
