### ISSUE TITLE
Word frequency/dictionary

### ISSUE THREAD

**Issue by iyayaya** [barrust/pyspellchecker#28]
Hi. We want to add some words to the dictionary but we were not able to find and access it. How can we possibly access the word frequency/dictionary? Also, can we limit the words suggested by the pyspellchecker cuz in some cases, it suggests a lot words after spell checking. 

Please help us out. Thank you!

**Comment by barrust** [comment]
You can access it through the `word_frequency` property. There are some examples in the [documentation](http://pyspellchecker.readthedocs.io/en/latest/).

You likely want to look at [this section of the quickstart](https://pyspellchecker.readthedocs.io/en/latest/quickstart.html#adding-and-removing-terms-from-a-dictionary)
