### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by iyayaya** [barrust/pyspellchecker#31]
Is there a way to make a user interface in this code? What plugins can you suggest? Thank you!
And also, is there another scientific solution to use in correcting the problems in capitalization? Thanks!

**Comment by barrust** [comment]
Yes! It is definitely possible to use pyspellchecker inside a user interface! I am not sure what you mean by plugin, but there are some python bindings to [common user interfaces](https://docs.python.org/3/faq/gui.html#id2) but this is not really in the realm of pyspellchecker. If you want to see an example of a command line program, there is one in the [quickstart](https://pyspellchecker.readthedocs.io/en/latest/quickstart.html#a-quick-command-line-spell-checking-program). 

As for the other question, it was decided to not deal with capitalization for several reasons: 
1) Adding capitalization doubles the alphabet needed to search which increases the time to complete
2) Capitalization is finicky and can be changed based on context. From [wiktionary.org](https://en.wiktionary.org/wiki/Appendix:English_proper_nouns):

> Many common nouns may be used as proper nouns; for example, mother is a common noun, as in “His mother just turned sixty-five”, but may be used as a proper noun, as in “Have you seen Mother today?”. As in this example, common nouns are traditionally capitalized when used as proper nouns.

There are also similar cases in many other languages. I am not an expert so I do not want to comment on another method to handle capitalization.

**Comment by iyayaya** [comment]
Thank you very much for your response!
