### ISSUE TITLE
Non-deterministic correction

### ISSUE THREAD

**Issue by Daval-G** [barrust/pyspellchecker#47]
When correcting a word, if the first candidates have the same probability it seems that the chosen one will depend on the dictionary (non) order. So the correction is non-deterministic in that case.

It would be great to add an arbitrary but constant order in that case.

**Comment by barrust** [comment]
@Daval-G thank you for pointing out this issue. Do you have ideas on what the best deterministic order would be for the result? Would alphabetical make sense? 

Also, do you have a good example case that can be used for testing?

**Comment by barrust** [comment]
@Daval-G if you have a concrete example, that would allow me to ensure that any fix provided would actually suffice. Thanks in advance!

**Comment by Daval-G** [comment]
Hi @barrust, thank you for your attention
I did not manage isolate the part of my code which revealed this problem, but it was fixed by changing the Counter in the word_frequency by an OrderedCounter (which impacted so hugely the performances that I just changed to another package). There is probably something smarter to do, for example when sorting the candidates.

Here is a simple piece of code to fix the arbitrary and non-deterministic behavior:
`from spellchecker import SpellChecker
spell = SpellChecker(language=None, distance=1)
spell.word_frequency.load_words("abcdefghijklmnop")
print(spell.correction("z"))
`
From there I get a different answer everytime I launch a new interactive session with Python 3.6.8. I accused the dictionaries but in Python 3.6 and higher the dictionary should be ordered, which makes it actually strange.

**Comment by barrust** [comment]
@Daval-G you are correct that an ordered dict would make the performance much slower in most use cases and only tracks insertion order. I have a solution that I just pushed to a branch that should provide the deterministic characteristics required without slowing down the library. 

If you have interest in testing, that would be very helpful! [hotfix/deterministic-correction](https://github.com/barrust/pyspellchecker/tree/hotfix/deterministic-correction)
