### ISSUE TITLE
Problem to set 'pt' language

### ISSUE THREAD

**Issue by lrthorita** [barrust/pyspellchecker#48]
SpellChecker is working for any  supported languages, except for Portuguese ('pt').
When I try using `spell = SpellChecker('pt')`, an error message appears saying:

`UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 587200: character maps to <undefined>`

I've also tried to load the dictionary the other way around:

`spell = SpellChecker(language=None)`
`spell.word_frequency.load_dictionary('path/to/pt.json.gz', encoding=u'utf-8')`

The same error occurs.

I'm using Python 3.6.8 in Windows 10.

**Comment by lrthorita** [comment]
I found out the problem.
In the `load_file` function at [spellchecker/utils.py](https://github.com/barrust/pyspellchecker/blob/master/spellchecker/utils.py), the `gzip.open` is not receiving the `encoding` argument.

Please, consider fixing it so the tool can operate correctly.

`def load_file(filename, encoding):
    """ Context manager to handle opening a gzip or text file correctly and
        reading all the data

        Args:
            filename (str): The filename to open
            encoding (str): The file encoding to use
        Yields:
            str: The string data from the file read
    """
    try:
        with gzip.open(filename, mode="rt"**, encoding=encoding**) as fobj:
            yield fobj.read()
    except (OSError, IOError):
        with OPEN(filename, mode="r", encoding=encoding) as fobj:
            yield fobj.read()`

**Comment by barrust** [comment]
Unfortunately, I am not seeing this issue on my mac or linux boxes in either python 3 or python 2.7 so this may be a windows specific issue.  

I am looking at forcing the encoding to the gzip.open function but that does not work in python 2.7. 

Could you provide the stack trace? That may help me find a workaround. 

Thanks!

**Comment by barrust** [comment]
There is a PR that ***should*** resolve your issue. Can you test? It is the [hotfix/gzip-encoding](https://github.com/barrust/pyspellchecker/tree/hotfix/gzip-encoding) branch

**Comment by lrthorita** [comment]
Hi @barrust! Thanks for answering.

Indeed, it seems this problem occurs only on Windows. However, I tried to debug the problem and changed that line I've suggested. It worked.

I'll test it.

**Comment by lrthorita** [comment]
@barrust, I tested the branch you asked. It is working.
