### ISSUE TITLE
Automatic Spell Check?

### ISSUE THREAD

**Issue by MalikRumi** [barrust/pyspellchecker#52]
Do I understand your examples correctly, that there is no way to point SpellChecker to a document and have it go through and auto-correct, like a word processor would do? I have to already know - or suspect - what words are misspelled and then ask SpellChecker to verify?

**Comment by barrust** [comment]
You are correct that you cannot point it at a file and have it fix everything. `pyspellchecker` is a library that would allow someone to build a tool that does something like that! There is no reason it could not be done but that is out of scope of this library.
