### ISSUE TITLE
Windows encoding errors not fixed in version 0.5.1

### ISSUE THREAD

**Issue by felix-schneider** [barrust/pyspellchecker#53]
On windows, spellchecker still has problems with encoding errors:

```python
import spellchecker
spell = spellchecker.SpellChecker("de")
# This word is correctly spelled
spell.known(["beschäftigen"])  # output: set()
spell.correction("beschäftigen")  # output: 'beschã¤ftigen'
spellchecker.__version__  # output: '0.5.1'
```

**Comment by barrust** [comment]
Can you confirm which version of python you are using? Unfortunately, I do not own a windows machine to do much testing but I did notice similar issues for your test case when using python 2.7.

**Comment by felix-schneider** [comment]
```bash
$ python --version
Python 3.7.3
```

Installed through anaconda for windows

**Comment by barrust** [comment]
I have some ideas to make sure that everything is always encoded (hopefully will have a hotfix branch out later today for testing) but I don't know if anything I do would fix the windows console issue. 

Can you run this test and post the output? 
``` python
import sys
sys.stdout.encoding
```

**Comment by felix-schneider** [comment]
```
$ python -c "import sys; print(sys.stdout.encoding)"
utf-8
```
Windows powershell uses utf-8 these days apparently.

**Comment by barrust** [comment]
Strange. I was under the impression that the windows console uses a different encoding. I will be pushing a branch this evening that ***might*** resolve it but I can't test it for windows since I do not have a windows machine. 

Any help you could provide would be much appreciated.

**Comment by barrust** [comment]
So, what is odd is that in Linux your example works perfectly. I get the correctly spelled word back (as expected) and everything prints just fine. 

Are you using a script or the shell for your test case example?
