### ISSUE TITLE
Spanish words are not corrected when they missed a tilde (`)

### ISSUE THREAD

**Issue by benjamimo1** [barrust/pyspellchecker#65]
Cancion != Canción

**Comment by barrust** [comment]
So, canción is in the dictionary but so is cancion: 

``` python
from spellchecker import SpellChecker

sc = SpellChecker(language='es')

print('canción' in sc)  # should be true
print('cancion' in sc)
print(sc.word_frequency['canción'])
print(sc.word_frequency['cancion'])
```

We can always clean up and remove words that are not truly correct (such as `cancion`). The dictionaries were built using an external project. Any support on finding and removing incorrect, or likely incorrect words, would be appreciated.

**Comment by benjamimo1** [comment]
thanks for your reply, although I don't have the time I appreciate the project and anyone who could be able to improve it.
