### ISSUE TITLE
What is your definition of "long"?

### ISSUE THREAD

**Issue by snoopyjc** [barrust/pyspellchecker#69]
"If the words that you wish to check are long, it is recommended to reduce the distance to 1".  How many characters do you recommend to use for "long"?

**Comment by barrust** [comment]
That is a personal preference. If your words are taking a long time using the default distance of 2, then try 1. 

See PR #61 as an example of longer words taking lots of time to complete.

**Comment by snoopyjc** [comment]
Thank you.  I just tested it, using my own dictionary, if len(word) >= 14, it starts taking over a second to return, so that's where I start using distance=1.  If len(word) > len(longest_word_in_dict)+2, then I don't bother checking the spelling, it's not right.
