### ISSUE TITLE
spellchecker.py:422: DeprecationWarning

### ISSUE THREAD

**Issue by pctjsm** [barrust/pyspellchecker#70]
Hi,
I´m getting this warning:
`....spellchecker.py:422: DeprecationWarning: 'encoding' is ignored and deprecated. It will be removed in Python 3.9`

Are you planning an update?

Thank you in advance.

**Comment by barrust** [comment]
Thank you for letting me know about this future deprecation warning. After doing some research it seems that it has been an ignored keyword for awhile. I will work on removing it from the next version of pyspellchecker.
