### ISSUE TITLE
 Damerau-Levenshtein metric

### ISSUE THREAD

**Issue by PeterPirog** [barrust/pyspellchecker#83]
Is possibile to add optionally Damerau-Levenshtein metric?

**Comment by barrust** [comment]
What do you mean by adding the Damerau-Levenshtein metric? Technically, the library does the following changes, up to edit distance of 2:
* insertion 
* deletion
* replacement
* transposition 

By edit distance of 2, that means, in this case, up to two of these actions.

**Comment by PeterPirog** [comment]
As I understand  basic operations (with distance 1) for Levenshtein  metric are insertion, deletion and replacement but for  Damerau-Levenshtein additionally basic operation is transposition too. 
In some practical cases I observed that transposition of letter is common:

weird  or werid
strength or strenght

These examples above has distance = 1 in Damerau-Levenshtein metric and distance =2 in Levenshtein metric, so it's nice to add option  to switch between  Levenshtein metric or Damerau-Levenshtein metric.

**Comment by barrust** [comment]
If you look at [the code here](https://github.com/barrust/pyspellchecker/blob/2ce8b9e8e9fc8b3e48eb7e17c8531a400ba4eb72/spellchecker/spellchecker.py#L211) you can see that we are already treating transposes as edit distance of 1. Are you not seeing transposition as an edit distance of 1?

**Comment by PeterPirog** [comment]
Thank you for the info. Maybe I did something wrong in my code.

**Comment by barrust** [comment]
Sounds good. If you are seeing it not do transpositions as distance 1, please let me know! If there is nothing else, I will close this ticket out in the next few days.

**Comment by barrust** [comment]
Using this test case, it looks like the transposition is working as expected. 

``` python
from spellchecker import SpellChecker

spell = SpellChecker(distance=1)
misspelled = spell.unknown(["trhee"])
print(misspelled)  # show it isn't correct
for word in misspelled:
    print(spell.edit_distance_1(word))
    print(spell.correction(word))
```

Please reopen this issue if you have an example of it not working as expected. Thanks!
