### ISSUE TITLE
Demography is changed to Geography in the latest version

### ISSUE THREAD

**Issue by prem2282** [barrust/pyspellchecker#85]
The word "Demography " is being spell corrected to "Geograpy", in the latest version.
In version 0.5.5 it is not so.

Could you please correct it?

**Comment by barrust** [comment]
Interesting! The building of all the supported dictionaries are automated and `demography` was only in the source file two times and was therefore removed from the dictionary for not being frequently used. (most words that are in the source just a few times are actually misspelled!) 

I am working on a solution to the automated script to ensure that certain words are in the dictionary.

**Comment by prem2282** [comment]
Thank you. Is it possible to add a dictionary with medical terminologies? I see most medical terms are not recognized.

**Comment by barrust** [comment]
I am happy to have medical terminology added to the dictionaries. It is just a rabbit hole that I do not have time to figure out. If someone built a specific dictionary, there could be a way that the library supported storing those types of dictionaries for others to use!
