### ISSUE TITLE
Change keyword args for build_dictionary.py

### ISSUE THREAD

**Issue by sviperm** [barrust/pyspellchecker#95]
I want to change keyword args in `_parse_args` function, `-p` and `-P` have similar letter, but different cases. 
Suggestion:
- `"-p", "--path"` -> `"-f", "--file_path"`
- `"-P", "--parse_input"` -> `"-p", "--parse_input"`

I can update code on next +- week, when I'll work on creating larger dictionary for Russian.

**Comment by barrust** [comment]
resolved by #102
