### ISSUE TITLE
Case Sensitive bug

### ISSUE THREAD

**Issue by cbsnagur** [barrust/pyspellchecker#99]
Case sensitive parameter has no affect bcz in "_parse_into_words" method text is made lower irrespective of case sensitive parameter, need to avoid it to make case-sensitive valid

**Comment by cbsnagur** [comment]
issue is tested and resolved with hotfix, 

@barrust  can you merge the changes and make a release, before i close the issue?

**Comment by barrust** [comment]
version 0.6.2 has been released.
